version: '3.8'
services:
  db:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - '27018:27017'
    restart: always
    networks:
      - pollvote_network
    volumes:
      - mongodb:/data/db
  myapp:
    image: viethd4a1/pollvoteapp:latest
    container_name: pollvoteapp-container 
    ports:
      # Biến PORT sẽ được đọc từ file .env
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    networks:
      - pollvote_network

networks:
  pollvote_network:
    driver: bridge

volumes:
  mongodb:
    driver: local